### ISSUE TITLE
improve Self Diagnostics and File Logging

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#1981]
The motivation for this change is to improve troubleshooting the SDK.
For several customers, it's problematic to make changes to their applications for the purpose of investigating the AI SDK. Some customers have safe-deployment requirements which can delay code changes by as much as a week from being deployed into production.

To address this several SDK teams contributed to this spec: https://github.com/microsoft/ApplicationInsights-Home/blob/master/CrossSdkCollaboration/Self-Diagnostics.md
The goal is for a SysAdmin or DevOps to be able to set an environment variable and to control the SDKs file logging.

### Tasks:
- [ ] 1. Add file logging into `DiagnosticsTelemetryModule`. #1724
    - [ ] Enable Environment Variable control as defined by the spec.
    - [ ] Retire `FileDiagnosticsTelemetryModule`. We don't need two ETW subscribers. 
    - [x] Need to refactor AspNetCore's dependency on `TelemetryConfiguration.Active`. #1886
- [ ] 2. Refactor severity. Need to set independently for File and Portal logging.
- [ ] 3. File Logging on by default (Stretch Goal)
    - [ ] Feature: must be more performant and remove the dependency on lock
    - [ ] Feature: control the file size
    - [ ] Feature: must be able to remove outdated log files.
