### ISSUE TITLE
End of Life for .NET 4.5.2, 4.6.0, 4.6.1 (April 26, 2022)

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2273]
## .NET versions 4.5.2, 4.6.0, and 4.6.1 are officially scheduled to reach end of life on [April 26, 2022](https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/#:~:text=on-,april%2026%2C%202022,-Jamshed)

- Official Statement: https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/
- .NET Framework Lifecycle FAQ: https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework

Using this Issue to track planned changes

- [x] ~~Official Recommendation is to migrate all projects to 4.6.2~~ this is cut.
  We made a decision to not migrate to 4.6.2. Our SDK already supports NetStandard2.0 which is compatible with NetFramework 4.6.2+. If we try to support both 4.6.2 and NetStandard2.0 we introduce more conflicts for customers. 
- [ ] Remove these frameworks from all projects
- [ ] Remove this framework from all build definitions
- [ ] Verify all projects have test coverage for all supported versions of dotnet
    - [ ] net4.6.2
    - [ ] net4.7.2
    - [ ] net4.8.0
    - [ ] NetCoreApp3.1
    - [ ] Net6.0

## Todo
- [x] what to do about projects that are net-framework only?
  Projects that only support a retiring version will not be updated.

**Comment by bigwheels490** [comment]
I am going to look into this in hopes of simplifying the work for issue #2439.

**Comment by bigwheels490** [comment]
@TimothyMothra Can I get some clarification on what is expected here?  It looks like it is calling to drop the explicit .Net Framework build altogether and only support .Net Standard.  Is that correct?  What about the projects that only target the .Net Framework?  Should I just remove them?
