### ISSUE TITLE
Repo Maintenance

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2466]
This issue is to track outstanding maintenance items for this repo.

- [x] move build output directory within repo directory. #2472
- [x] Readme: display latest Stable and Beta packages #2474
- [x] Replace two branches (master/develop) with a single branch (main). #2474
- [x] Remove Bond if possible (causing compliance issues). [BASE\ApplicationInsightsTypes](https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/BASE/Test/Microsoft.ApplicationInsights.Test/ApplicationInsightsTypes), [NETCORE\ApplicationInsightsTypes](https://github.com/microsoft/ApplicationInsights-dotnet/tree/develop/NETCORE/test/ApplicationInsightsTypes)
- [x] Archive old perf/docker tests (no longer used, no longer functional). #2486
- [x] Confirm all projects/solutions have a "sanity" build that at minimum successfully compiles. #2487
- [ ] Expand Redfield build/tests to cover entire repo (currently only verifies Base).
- [ ] Docker + SQL for unit tests.
- [x] Need to audit all new Github Workflows to verify external contributors cannot queue any workflow with secrets.
- [ ] Consolidate Readme/Contributing docs
- [x] Migrate all unit tests from Azure DevOps to Github Workflow #2483
