### ISSUE TITLE
new signing pipeline

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2475]
This issue is for tracking the migration to the new signing pipelines.

### TODO
- New Builds
    - [x] Get pipeline created
    - [x] Get pipeline running "Official"
    - [x] Permission issue: "This account and pool are not onboarded to this service."
    - [x] How to enable Redfield builds? "Official.Redfield"
    - [x] Can we have a definition to run compliance tools for PRs? "Buddy"
    - [x] how to correctly trigger "Buddy" builds for PRs?
      (This will run our compliance tools. I currently have a support ticket to help with this.)
- Build Output
    - [x] build output is in a directory above source. This directory is inaccessible for scripting.
    - [x] Nupkgs are signed, DLLs are not
    - [x] DLLs are signed with wrong cert
    - [x] Need to generate release metadata file
- Compliance Tools
    - [x] Resolve compliance issues.
    - [x] Run compliance tools on "Buddy" build for PRs.
    - [ ] How to run custom Audit script?
- Other
    - [ ] Rename all build params to explicitly describe what settings they affect

**Comment by TimothyMothra** [comment]
These are the build params used:

- NIGHTLY
  - `-p:NightlyBuild=True -p:PublicRelease=True`
- BUDDY
  - `-p:OfficialRelease=True`
- OFFICIAL
  - `-p:PublicRelease=True -p:StableRelease=True -p:OfficialRelease=True`
- REDFIELD
  - `-p:PublicRelease=True -p:StableRelease=True -p:OfficialRelease=True -p:Redfield=True`

This is what these build params control:

- OfficialRelease
  - _Nupkg.props
    - build properties for nupkg
- PublicRelease
  - _Signing.props
    - Defines to use real signing.
- StableRelease
  - _GlobalStaticVersion.props
    - Controls version for nupkg
- Redfield
  - Directory.Build.props
    - Logging
  - _GlobalStaticVersion.props
    - controls version for dll and nupkg
- NightlyBuild
  - _GlobalStaticVersion.props
    - controls version for dll and nupkg


--
Builds can be difficult to troubleshoot because the names don't describe what settings they affect.
