### ISSUE TITLE
Support for .NET7 (November 2022)

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2578]
Opening this issue to track supporting .NET 7.

Assumed release date is Nov 11, listed on dotnet's milestone: https://github.com/dotnet/runtime/milestone/82

### Tracking Previews
- Preview 3 was released on April 13th: https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-3/
- Preview 6 was released on July 12th: https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-6/
- Preview 7 was released on August 9th: https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-7/
- Release Candidate 1 was released on September 14th: https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-rc-1/
- Release Candidate 2 was released on October 11th: https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-rc-2/
- GA Nov 8th: https://devblogs.microsoft.com/dotnet/announcing-dotnet-7/

## TODO
- [x] Update builds, add support for latest .NET 7 Preview
- [x] Update test matrix, add .NET 7
- [x] remove "preview" from builds after .NET 7 official release (Nov)

**Comment by avisra** [comment]
Application insights is greyed out on my .NET 7 project - is this intended? When do we think it will be supported if so? (I'll probably need to roll back to .NET 6.. as application insights is a must if in azure)

**Comment by vishweshbankwar** [comment]
@avisra - Could you please confirm where it is grayed out. Is it grayed out while creating the webapp or is it grayed out in Application Insights blade (shown below) within your webapp?
![image](https://user-images.githubusercontent.com/17655898/201244424-944c452d-f108-42b9-abf8-77fee443b1c0.png)

**Comment by vishweshbankwar** [comment]
@avisra - we are looking in to this. In the meantime you can use the following workaround
1. Create a new application insights resource.
2. Set the following AppSettings in your app to enable it–
APPINSIGHTS_INSTRUMENTATIONKEY – “<Instrumentation key>”
APPLICATIONINSIGHTS_CONNECTION_STRING – “<Connection string>”
ApplicationInsightsAgent_EXTENSION_VERSION – “~2” (for windows) , “~3” (for linux)

**Comment by avisra** [comment]
@vishweshbankwar When viewing the App Service, the "Application Insights" menu option in the left blade is greyed out. When we hover over it, it says "Application Insights is not supported for your app's runtime configuration"

I will try the steps you mention here shortly

**Comment by avisra** [comment]
Data is tracking to my application insights instance now - but the blade is still greyed out. Thank you for the workaround. I'll keep an eye on this thread for the official fix

**Comment by dirtygooback** [comment]
Why is this closed? The issue is still there. I also have "application insights" greyed out on the blade when switching to .net 7

**Comment by mvdgun** [comment]
Same issue here, all the keys were correct but the ApplicationInsightsAgent_EXTENSION_VERSION setting was set to ~2. Changing it to ~3 fixed it for me (I'm running on Linux). The blade in the app service is still greyed out though, same issue as @avisra.

**Comment by cijothomas** [comment]
> Why is this closed? The issue is still there. I also have "application insights" greyed out on the blade when switching to .net 7

This issue is only for tracking sdk support for .net 7 which is done.
