### ISSUE TITLE
Support for .NET8 (November 2023)

### ISSUE THREAD

**Issue by TimothyMothra** [microsoft/ApplicationInsights-dotnet#2711]
Opening this issue to track supporting .NET 8.

Assumed release date is Nov 10, listed on dotnet's milestone: https://github.com/dotnet/runtime/milestone/99

### Tracking Releases
- TBD

## TODO
- [ ] Update builds, add support for latest .NET 8 Preview
- [ ] Update test matrix, add .NET 8
- [ ] remove "preview" from builds after .NET 8 official release (Nov)
